# This Cloud Build configuration file builds a Docker image and pushes it to Google Container Registry.
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "GEMINI_API_KEY=${_GEMINI_API_KEY}" >> .env
        echo "FIREBASE_SERVICE_ACCOUNT_JSON=${_FIREBASE_SERVICE_ACCOUNT_JSON}" >> .env
        echo "FIREBASE_REALTIME_DB=${_FIREBASE_REALTIME_DB}" >> .env
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${LOCATION}-docker.pkg.dev/$PROJECT_ID/${_PROJECT_NAME}/${_IMAGE_NAME}:${COMMIT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${LOCATION}-docker.pkg.dev/$PROJECT_ID/${_PROJECT_NAME}/${_IMAGE_NAME}:${COMMIT_SHA}']

images:
  - '${LOCATION}-docker.pkg.dev/$PROJECT_ID/${_PROJECT_NAME}/${_IMAGE_NAME}:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY